all: clean build run

clean: # remove data and binary folder

build: # compile to binary (if you use interpreter, then do not implement it)

run: 
	python src/main.py

nt:
	python src/national-park.py	

f:
	python src/fauna.py	